### ISSUE TITLE
Problem with sharppcap when running in Linux environment 

### ISSUE THREAD

**Issue by rysavy-ondrej** [rysavy-ondrej/Distance#1]
```
Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'wpcap' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libwpcap: cannot open shared object file: No such file or directory
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_open_offline(String fname, StringBuilder errbuf)
   at SharpPcap.LibPcap.CaptureFileReaderDevice..ctor(String captureFilename)
   at Distance.Engine.Program.Main(String[] args) in /distance/DistanceEngine/Program.cs:line 62
Aborted
```

**Comment by rysavy-ondrej** [comment]
We do not rely on SharpPcap any more.
